/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.


*/

#include<array>
#include "hwlib.hpp"
#include "library.hpp"




int main( void ){

  moving mover;
 moving testmover;
moving moverduo;
   auto led =hwlib::target::pin_out(1,27);
   auto switc =hwlib::target::pin_in(1,25);		//pin 2
   auto switcsto =hwlib::target::pin_in(2,28);
	hwlib::wait_ms(200);
   auto pot =   hwlib::target::pin_adc( due::ad_pins::a1 );
   auto potpan =   hwlib::target::pin_adc( due::ad_pins::a2 );
   auto pottilt =   hwlib::target::pin_adc( due::ad_pins::a3 );
   auto potcolor =   hwlib::target::pin_adc( due::ad_pins::a4 );

	int waarde= (pot.read()/16);
	int waardetilt= (pot.read()/16);
	int waardedim= (pot.read()/16);
	dmx512 outp(0);
	int moverno = outp.addtopatch(mover,50);
	int movernoduo = outp.addtopatch(moverduo,60);	
	int testmoverno = outp.addtopatch(testmover,10);
	int opstartmode =0;
	int waardein=0;
	int tilt2=0;
	int state=0;
if((pot.read()/16)>200){opstartmode=0;}
else if((pot.read()/16)<50){opstartmode=2;}
else{opstartmode=1;}
hwlib::cout <<"pass   "<<opstartmode;
while(1){
if(switcsto.read()==0){	opstartmode =0;}
if(opstartmode==0){
if(state==0){
	hwlib::cout<<state<<hwlib::endl;
   while(1){

		if(abs(waarde-(potpan.read()/16))>1 || abs((potpan.read()/16)-waarde)>1){
			waarde = (potpan.read()/16); waardein=255-waarde;
}
		if(abs(waardetilt-(pottilt.read()/16))>2 || abs((pottilt.read()/16)-waardetilt)>2){
					waardetilt = (pottilt.read()/16); tilt2=(pottilt.read()/16);
		}
		if(abs(waardedim-(pot.read()/16))>2 || abs((pot.read()/16)-waardedim)>2){
					waardedim = (pot.read()/16);
		}
		if(switc.read()==0){state++; while(true){if(switc.read() ==1){break;}}break;}
		if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}

		mover.sendstream(waarde,waardetilt,(potcolor.read()/16),waardedim);
	
		moverduo.sendstream(waarde,waardetilt,(potcolor.read()/16),waardedim);		
	
		outp.updatefixture(mover, moverno);
		outp.updatefixture(moverduo, movernoduo);		
		outp.fixtureout();

}
}
if(state==1){
	hwlib::cout<<state<<hwlib::endl;
   while(1){

		if(abs(waarde-(potpan.read()/16))>1 || abs((potpan.read()/16)-waarde)>1){
			waarde = (potpan.read()/16); waardein=255-waarde;
}
		if(abs(waardetilt-(pottilt.read()/16))>2 || abs((pottilt.read()/16)-waardetilt)>2){
					waardetilt = (pottilt.read()/16); tilt2=(pottilt.read()/16);
		}
		if(abs(waardedim-(pot.read()/16))>2 || abs((pot.read()/16)-waardedim)>2){
					waardedim = (pot.read()/16);
		}
		if(switc.read()==0){state++; while(true){if(switc.read() ==1){break;}}break;}
		if(switcsto.read()==0){	mover.strobestart();}else{mover.strobestop();}

		mover.sendstream(waarde,waardetilt,(potcolor.read()/16),waardedim);

		outp.updatefixture(mover, moverno);		
		outp.fixtureout();


}
}
if(state==2){
	hwlib::cout<<state<<hwlib::endl;
   while(1){

		if(abs(waarde-(potpan.read()/16))>1 || abs((potpan.read()/16)-waarde)>1){
			waarde = (potpan.read()/16); waardein=255-waarde;
}
		if(abs(waardetilt-(pottilt.read()/16))>2 || abs((pottilt.read()/16)-waardetilt)>2){
					waardetilt = (pottilt.read()/16); tilt2=(pottilt.read()/16);
		}
		if(abs(waardedim-(pot.read()/16))>2 || abs((pot.read()/16)-waardedim)>2){
					waardedim = (pot.read()/16);
		}
		if(switc.read()==0){state++; while(true){if(switc.read() ==1){break;}}break;}
		if(switcsto.read()==0){moverduo.strobestart();}else{moverduo.strobestop();}
	
		moverduo.sendstream(waarde,waardetilt,(potcolor.read()/16),waardedim);		
	

		outp.updatefixture(moverduo, movernoduo);		
		outp.fixtureout();


}
}
if(state==3){
	hwlib::cout<<state<<hwlib::endl;
   while(1){
		//hwlib::cout<<abs(waarde-(potpan.read()/16))<<"       "<<abs((potpan.read()/16)-waarde)<<'\n';
		if(abs(waarde-(potpan.read()/16))>1 || abs((potpan.read()/16)-waarde)>1){
			waarde = (potpan.read()/16); waardein=255-waarde;
}
		if(abs(waardetilt-(pottilt.read()/16))>2 || abs((pottilt.read()/16)-waardetilt)>2){
					waardetilt = (pottilt.read()/16); tilt2=(pottilt.read()/16);
		}
		if(abs(waardedim-(pot.read()/16))>2 || abs((pot.read()/16)-waardedim)>2){
					waardedim = (pot.read()/16);
		}
		if(switc.read()==0){state=0; while(true){if(switc.read() ==1){break;}}break;}
		if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}

		mover.sendstream(waarde,waardetilt,(potcolor.read()/16),waardedim);
		
		moverduo.sendstream((255-waarde),waardetilt,(potcolor.read()/16),waardedim);		
		
		outp.updatefixture(mover, moverno);
		outp.updatefixture(moverduo, movernoduo);		
		outp.fixtureout();

}
}
}
else if(opstartmode == 1){
	hwlib::cout<<"mode1";


	while(1){



	if(switc.read()==0){opstartmode =2; while(true){if(switc.read() ==1){break;}} hwlib::wait_ms(5); break;}
	if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}


	for(int i=0; i<255; i++){
	if(switc.read()==0){opstartmode =2;break;}
	
	if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}
	waarde = 2*(pot.read()/16)+400;

	if(abs(waardetilt-(potpan.read()/16))>1 || abs((potpan.read()/16)-waardetilt)>1){
			waardetilt = (potpan.read()/16);
	}

	mover.sendstream(waardetilt,10,(potcolor.read()/16),(pottilt.read()/16));
	moverduo.sendstream(255-waardetilt,10,(potcolor.read()/16),(pottilt.read()/16));
	outp.updatefixture(mover, moverno);
	outp.updatefixture(moverduo, movernoduo);		
	outp.fixtureout();
	hwlib::wait_ms(waarde);
	if(abs(waardetilt-(potpan.read()/16))>1 || abs((potpan.read()/16)-waardetilt)>1){
			waardetilt = (potpan.read()/16);
	}
	if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}
	mover.sendstream(waardetilt,245,(potcolor.read()/16),(pottilt.read()/16));
	moverduo.sendstream(255-waardetilt,245,(potcolor.read()/16),(pottilt.read()/16));
	outp.updatefixture(mover, moverno);
	outp.updatefixture(moverduo, movernoduo);
	outp.fixtureout();

	hwlib::wait_ms(waarde);
	}

}
}
else if(opstartmode ==2){
	while(1){
	if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}
	if(switc.read()==0){opstartmode =1; while(true){if(switc.read() ==1){break;}}hwlib::wait_ms(5);break;}
	for(int i=0; i<255; i++){
	if(switc.read()==0){opstartmode =1;break;}
	if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}
	if(abs(waardetilt-(potpan.read()/16))>1 || abs((potpan.read()/16)-waardetilt)>1){
			waardetilt = (potpan.read()/16);}
	
	waarde = (pot.read()/16);
	mover.sendstream(waardetilt,(i),(potcolor.read()/16),(pottilt.read()/16));
	moverduo.sendstream(waardetilt,(i),(potcolor.read()/16),(pottilt.read()/16));
	outp.updatefixture(mover, moverno);
	outp.updatefixture(moverduo, movernoduo);		
	outp.fixtureout();
	hwlib::wait_ms(waarde/2);
	}
	for(int i=0; i<255; i++){
	if(switc.read()==0){opstartmode =1;break;}
	if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}
	waarde = (pot.read()/16);
	if(abs(waardetilt-(potpan.read()/16))>1 || abs((potpan.read()/16)-waardetilt)>1){
			waardetilt = (potpan.read()/16);}
	mover.sendstream(waardetilt,(255-i),(potcolor.read()/16),(pottilt.read()/16));
	moverduo.sendstream(waardetilt,(255-i),(potcolor.read()/16),(pottilt.read()/16));
	outp.updatefixture(mover, moverno);
	outp.updatefixture(moverduo, movernoduo);			
	outp.fixtureout();
	hwlib::wait_ms(waarde/2);
	
	}

}
}
else if(testmoverno == 1){
hwlib::cout<<"say whattttt"; 
}
}
}









      








