/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.


*/

#include<array>
#include "hwlib.hpp"
#include "library.hpp"
/*
this test will first move the moving heads, with all user editable parameters rising except for color staying white, then going back to zero, here the color will scroll, this sequence is to test the implementation of fixtures in dmx512 and the moving class
then it will command a led PAR to change color, first increasing red to 255, than green and finally blue, this then loops, this is to test the senddata() in dmx512, aka sending data directly to dmx

*/

int main( void ){

  moving mover;

moving moverduo;
   auto led =hwlib::target::pin_out(1,27);
   auto switc =hwlib::target::pin_in(1,25);		//pin 2
   auto switcsto =hwlib::target::pin_in(2,28);
	hwlib::wait_ms(200);
   auto pot =   hwlib::target::pin_adc( due::ad_pins::a1 );
   auto potpan =   hwlib::target::pin_adc( due::ad_pins::a2 );
   auto pottilt =   hwlib::target::pin_adc( due::ad_pins::a3 );
   auto potcolor =   hwlib::target::pin_adc( due::ad_pins::a4 );

	int waarde= (pot.read()/16);
	int waardetilt= (pot.read()/16);
;
	dmx512 outp(0);
	int moverno = outp.addtopatch(mover,50);
	int movernoduo = outp.addtopatch(moverduo,60);	
	
	int opstartmode =0;



	while(1){
	for(int i=0; i<255; i++){
	if(abs(waardetilt-(potpan.read()/16))>1 || abs((potpan.read()/16)-waardetilt)>1){
			waardetilt = (potpan.read()/16);}
	
	waarde = (pot.read()/16);
	mover.sendstream(i,(i),(potcolor.read()/16),i);
	moverduo.sendstream(i,(i),(potcolor.read()/16),i);
	outp.updatefixture(mover, moverno);
	outp.updatefixture(moverduo, movernoduo);		
	outp.fixtureout();
	hwlib::wait_ms(waarde/2);
	}
	for(int i=0; i<255; i++){
	if(switc.read()==0){opstartmode =1;break;}
	if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}
	waarde = (pot.read()/16);
	if(abs(waardetilt-(potpan.read()/16))>1 || abs((potpan.read()/16)-waardetilt)>1){
			waardetilt = (potpan.read()/16);}
	mover.sendstream((255-i),(255-i),(255-i),(255-i));
	moverduo.sendstream((255-i),(255-i),(255-i),(255-i));
	outp.updatefixture(mover, moverno);
	outp.updatefixture(moverduo, movernoduo);			
	outp.fixtureout();
	hwlib::wait_ms(waarde/2);
	}
	for(int k=0; k<255; k++){
	if(switc.read()==0){opstartmode =1;break;}
	if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}
	waarde = (pot.read()/16);
	if(abs(waardetilt-(potpan.read()/16))>1 || abs((potpan.read()/16)-waardetilt)>1){
			waardetilt = (potpan.read()/16);}
	outp.senddata({255,k,0,0},4);
	hwlib::wait_ms(waarde/2);
	}
	for(int k=0; k<255; k++){
	if(switc.read()==0){opstartmode =1;break;}
	if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}
	waarde = (pot.read()/16);
	if(abs(waardetilt-(potpan.read()/16))>1 || abs((potpan.read()/16)-waardetilt)>1){
			waardetilt = (potpan.read()/16);}
	outp.senddata({255,255,k,0},4);
	hwlib::wait_ms(waarde/2);
	}
	for(int k=0; k<255; k++){
	if(switc.read()==0){opstartmode =1;break;}
	if(switcsto.read()==0){	mover.strobestart();moverduo.strobestart();}else{mover.strobestop(); moverduo.strobestop();}
	waarde = (pot.read()/16);
	if(abs(waardetilt-(potpan.read()/16))>1 || abs((potpan.read()/16)-waardetilt)>1){
			waardetilt = (potpan.read()/16);}
	outp.senddata({255,255,255,k},4);
	hwlib::wait_ms(waarde/2);
	}


}


}








      








